version: '3.3'
services:

  frontend:
    image: deorz/foodgram_front
    volumes:
      - ../frontend/:/app/result_build/
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    image: deorz/yandex_foodgram
    restart: always
    volumes:
      - static_value:/backend/foodgram/foodgram_static/
      - media_value:/backend/foodgram/foodgram_media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/backend/static/
      - media_value:/backend/media/
    depends_on:
      - frontend
      - backend

volumes:
  static_value:
  media_value:
  postgres_value: